# Generated by Django 2.1.7 on 2019-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mapUEL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sURL', models.CharField(max_length=6)),
                ('lURL', models.CharField(max_length=512)),
                ('created', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
